<?php

namespace Novatech\StockBundle\Repository;

/**
 * ApprovisionerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprovisionerRepository extends \Doctrine\ORM\EntityRepository
{
}
