<?php

namespace Novatech\StockBundle\Repository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends \Doctrine\ORM\EntityRepository
{
	public function getStockByProduitId($id)
    {
	  $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $query = $queryBuilder
            ->select('s')
            ->from ('StockBundle:Stock','s')
            ->innerJoin('s.produit', 'p')
            ->where('p.id = :id')
            ->setParameter('id',$id)
        ;

        return $query
            ->getQuery()
            ->getResult()
            ;
    }
    
    public function getHistoriqueByStockId($id)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $query = $queryBuilder
            ->select('sf')
            ->from ('StockBundle:StockFournisseur','sf')
            ->innerJoin('sf.stock', 's')
            ->innerJoin('sf.fournisseur', 'f')
            ->innerJoin('s.produit', 'p')
            ->where('p.id = :id')
            ->setParameter('id',$id)
        ;

        return $query
            ->getQuery()
            ->getResult()
            ;
    }

    public function getNombreProduitStock()
    {
	  $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $query = $queryBuilder
            ->select('count(s.id) as nombre')
            ->from ('StockBundle:Stock','s')
            ->innerJoin('s.produit', 'p')
            ->where('s.quantiteProduit > 0')
        ;

        return $query
            ->getQuery()
            ->getResult()
            ;
    }
}
