<?php

namespace Novatech\StockBundle\Repository;

/**
 * StockFournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockFournisseurRepository extends \Doctrine\ORM\EntityRepository
{
}
