<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAenkydn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAenkydn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAenkydn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAenkydn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAenkydn\appProdProjectContainer(array(
    'container.build_hash' => 'Aenkydn',
    'container.build_id' => 'f9a97034',
    'container.build_time' => 1564420674,
));
