<?php

namespace Banque\CompteBundle\Repository;

/**
 * OperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllOperationByTypeAndCompte($compte, $type)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $query = $queryBuilder
            ->select('o')
            ->from ('CompteBundle:Operation','o')
            ->innerJoin('o.compte', 'c')
            ->where('c.id = :idCompte and o.typeOperation = :typeOperation')
            ->setParameter('idCompte',$compte)
            ->setParameter('typeOperation',$type)
        ;

        return $query
            ->getQuery()
            ->getResult()
            ;
    }
}
