<?php

namespace Novatech\ProduitBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastId()
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $query = $queryBuilder
            ->select('p.id')
            ->from ('ProduitBundle:Produit','p')
            ->orderBy('p.id',"DESC")
            ->setMaxResults(1)
        ;
        return $query->getQuery()->getResult();
    }
}
