<?php

namespace Novatech\ProduitBundle\Repository;

/**
 * TypeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllProduitByTypeProduitId($id)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $query = $queryBuilder
            ->select('p')
            ->from ('ProduitBundle:Produit','p')
            ->innerJoin('p.typeProduit', 'tp')
            ->where('tp.id = :id')
            ->setParameter('id',$id)
        ;

        return $query
            ->getQuery()
            ->getResult()
            ;
    }
}
