<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3cfm2ee\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3cfm2ee/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3cfm2ee.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3cfm2ee\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3cfm2ee\appDevDebugProjectContainer([
    'container.build_hash' => '3cfm2ee',
    'container.build_id' => '5efd4513',
    'container.build_time' => 1674164915,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3cfm2ee');
