<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKvrchuj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKvrchuj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKvrchuj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKvrchuj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKvrchuj\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kvrchuj',
    'container.build_id' => 'b14fc8c0',
    'container.build_time' => 1564420645,
));
